// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOvED2NHVn5HqbJuT1aATNN44ZHRbNFmM',
    appId: '1:1011328312096:web:efa9245047f749b1a6ad45',
    messagingSenderId: '1011328312096',
    projectId: 'room-mangement',
    authDomain: 'room-mangement.firebaseapp.com',
    storageBucket: 'room-mangement.appspot.com',
    measurementId: 'G-41ZD8SKQSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6mFeXaM4EFqZTIMreumR_mrqnY5K8-Cw',
    appId: '1:1011328312096:android:dcf706f2b6c34fd5a6ad45',
    messagingSenderId: '1011328312096',
    projectId: 'room-mangement',
    storageBucket: 'room-mangement.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhEfzIpE9FVuyj5HepNE1E8Wh0KaL2h1c',
    appId: '1:1011328312096:ios:d7abfac9ffb9061ca6ad45',
    messagingSenderId: '1011328312096',
    projectId: 'room-mangement',
    storageBucket: 'room-mangement.appspot.com',
    iosClientId:
        '1011328312096-44jvo48t78ludartohm9ahlp3oo9ivb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.appQlphongtroSv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhEfzIpE9FVuyj5HepNE1E8Wh0KaL2h1c',
    appId: '1:1011328312096:ios:2a7126e24cac61b0a6ad45',
    messagingSenderId: '1011328312096',
    projectId: 'room-mangement',
    storageBucket: 'room-mangement.appspot.com',
    iosClientId:
        '1011328312096-708q8qcs6h2nk9gm3obk5dd5edom2pde.apps.googleusercontent.com',
    iosBundleId: 'com.example.appQlphongtroSv.RunnerTests',
  );
}
